os: "WMF 5"
version: 1.0.{build}

environment:
  ModuleName: "Communary.ConsoleExtensions"
  psGalleryKey:
    secure: bsxEMSo9+lWrKb0usvlB8RtvGgFcVfV1XxLDjBmP5NwrFv5CHWXAxs2YGQrkJffc

branches:
  only:
    - master

skip_commits:
  message: /updated readme.*/

install:
  - ps: Get-PackageProvider -Name NuGet -ForceBootstrap | Out-Null

build: off

test: off

deploy_script:
  - ps: |
      if ((! $ENV:APPVEYOR_PULL_REQUEST_NUMBER) -and ($ENV:APPVEYOR_REPO_BRANCH -eq 'master')) {
        Write-Host 'Publishing module to PowerShell Gallery'
        [System.Version]$buildNumber = $env:APPVEYOR_BUILD_VERSION
        Update-ModuleManifest -Path ".\$($env:ModuleName).psd1" -ModuleVersion $buildNumber
        Test-ModuleManifest -Path ".\$($env:ModuleName).psd1"
        Push-AppveyorArtifact ".\$($env:ModuleName).psd1"
        $moduleFiles = Get-ChildItem *
        $moduleDirectory = New-Item -Path $env:ModuleName -Type Directory
        Copy-Item -Path $moduleFiles -Destination $moduleDirectory -Recurse
        Test-ModuleManifest -Path "$(Join-Path $moduleDirectory $env:ModuleName)\$($env:ModuleName).psd1"
        Publish-Module -Path $moduleDirectory -NuGetApiKey $env:psGalleryKey -Verbose
      }
